# Generated by Django 3.2 on 2023-08-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0003_sprofile_tprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SProfile',
        ),
    ]
