# Generated by Django 3.2 on 2023-08-26 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0006_user_pfimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50)),
                ('year', models.CharField(choices=[('0', 'Select Year'), ('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], default='0', max_length=5)),
                ('subject', models.CharField(max_length=50)),
                ('descnote', models.CharField(max_length=10)),
                ('ntfle', models.FileField(upload_to='DataFiles')),
                ('date_created', models.DateField(auto_now=True)),
                ('sckey', models.CharField(max_length=10)),
                ('usr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
