# Generated by Django 3.2 on 2023-08-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NotesApp', '0007_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='usr_id',
            new_name='usr',
        ),
    ]
